In [1]:
import numpy as np
import pandas as pd

### Read Base Output - Processed from raw data

In [5]:
%%time
base_output_df = pd.read_csv('../data/processed/output.csv')

CPU times: user 1.64 s, sys: 200 ms, total: 1.84 s
Wall time: 1.84 s

In [6]:
base_output_df.head()

,Date,Segment,Period,Type,Subtype,Value
0,1974-12-31,Europe,On Trailing EY,Market,EURO,27536.0
1,1974-12-31,Consumer Discretionary,On Trailing EY,Sectors,EURO_25,26861.0
2,1974-12-31,Consumer Staples,On Trailing EY,Sectors,EURO_30,25887.8
3,1974-12-31,Energy,On Trailing EY,Sectors,EURO_10,51400.2
4,1974-12-31,Financials,On Trailing EY,Sectors,EURO_40,28288.0

In [19]:
base_output_df['Date'] = pd.to_datetime(base_output_df['Date'])

### Overivew of data

In [7]:
base_output_df['Segment'].value_counts()

Telecommunication Services                        111340
Materials                                         111340
Energy                                            111340
Utilities                                         111340
Real Estate                                        55670
Transportation                                     55670
Automobiles & Components                           55670
Household & Personal Products                      55670
Media                                              55670
United Kingdom                                     55670
Consumer Staples                                   55670
Finland                                            55670
Industrials                                        55670
Technology Hardware & Equipment                    55670
Financials                                         55670
Commercial & Professional Services                 55670
Capital Goods                                      55670
Consumer Durables & Apparel                        55670
Sweden                                             55670
Belgium                                            55670
Netherlands                                        55670
Information Technology                             55670
Insurance                                          55670
Food, Beverage & Tobacco                           55670
Health Care Equipment & Services                   55670
Retailing                                          55670
Health Care                                        55670
Food & Staples Retailing                           55670
Spain                                              55670
Consumer Discretionary                             55670
Semiconductors & Semiconductor Equipment           55670
Consumer Services                                  55670
Switzerland                                        55670
Diversified Financials                             55670
Banks                                              55670
Software & Services                                55670
Germany                                            55670
Pharmaceuticals, Biotechnology & Life Sciences     55670
Italy                                              55670
France                                             55670
Norway                                             55670
Portugal                                           55670
Europe                                             55670
Ireland                                            55670
Denmark                                            55670
Austria                                            55670
Greece                                             55670
Name: Segment, dtype: int64

In [10]:
base_output_df['Period'].value_counts()

On Trailing DY     567834
On Forward EY      567834
On Forward DY      567834
On Trailing EY     567834
On Trailing BVY    567834
Name: Period, dtype: int64

In [9]:
base_output_df['Type'].value_counts()

Industry Groups    1336080
Countries           890720
Sectors             556700
Market               55670
Name: Type, dtype: int64

In [11]:
base_output_df['Subtype'].value_counts()

PT           55670
SE           55670
EURO_45      55670
BE           55670
EURO_2030    55670
EURO_20      55670
EURO_4530    55670
EURO_4020    55670
EURO_25      55670
ES           55670
EURO_2010    55670
EURO_35      55670
GB           55670
AT           55670
EURO_40      55670
EURO_4010    55670
EURO_2520    55670
CH           55670
IE           55670
GR           55670
EURO_3010    55670
EURO_2540    55670
EURO_5510    55670
EURO         55670
DK           55670
IT           55670
EURO_3510    55670
EURO_30      55670
FR           55670
NL           55670
EURO_3030    55670
EURO_55      55670
EURO_2020    55670
EURO_50      55670
NO           55670
EURO_4520    55670
EURO_2550    55670
EURO_1010    55670
DE           55670
EURO_4030    55670
EURO_2510    55670
FI           55670
EURO_3020    55670
EURO_2530    55670
EURO_10      55670
EURO_15      55670
EURO_1510    55670
EURO_3520    55670
EURO_5010    55670
EURO_4040    55670
EURO_4510    55670
Name: Subtype, dtype: int64

### 1 - Sum of Billings by country

In [16]:
billing_by_ctry = base_output_df[base_output_df['Type'] == 'Countries'].groupby('Subtype')['Value'].sum().reset_index(drop=False)

In [27]:
billing_by_ctry.columns = ['Countries', 'Billings']

In [28]:
billing_by_ctry

   Countries     Billings
0         AT   74103620.8
1         BE   87917478.2
2         CH  104617768.2
3         DE  106702182.0
4         DK  128206611.6
5         ES   98959061.0
6         FI   60853596.0
7         FR  102490130.8
8         GB   93540781.8
9         GR   14181895.0
10        IE   81519071.0
11        IT  116358047.2
12        NL  104444243.0
13        NO  109394855.6
14        PT   19975413.4
15        SE   79518933.2

### 2 - Sum of billing by period for type = market from 2016 to present (include Jan, 1, 2016)

In [29]:
billing_by_period = base_output_df[
    (base_output_df['Type'] == 'Market')
    & (base_output_df['Date'].dt.year >= 2016)
].groupby('Period')['Value'].sum().reset_index(drop=False)

In [30]:
billing_by_period.columns = ['Period', 'Billings']

In [31]:
billing_by_period

            Period    Billings
0    On Forward DY   8187891.2
1    On Forward EY   5374587.4
2  On Trailing BVY  14551959.2
3   On Trailing DY   9283540.2
4   On Trailing EY   8567728.0

### 3 - Summary Statistics by Segment

In [25]:
segment_summary_stat = base_output_df.groupby('Segment').describe()

In [26]:
segment_summary_stat

                                                  Value                \
                                                  count          mean
Segment
Austria                                          5068.0  14621.866772
Automobiles & Components                         5130.0  17993.555244
Banks                                            5144.0  14870.369984
Belgium                                          5097.0  17248.867608
Capital Goods                                    5198.0  14757.024240
Commercial & Professional Services               4820.0  13740.753610
Consumer Discretionary                           5204.0  20033.360492
Consumer Durables & Apparel                      5194.0  17167.212206
Consumer Services                                5108.0  13109.457674
Consumer Staples                                 5203.0  14831.561983
Denmark                                          5113.0  25074.635556
Diversified Financials                           5125.0  17877.532878
Energy                                          10242.0  27564.776333
Europe                                           5205.0  20549.080192
Financials                                       5202.0  15646.698847
Finland                                          4617.0  13180.332684
Food & Staples Retailing                         5185.0  13806.779016
Food, Beverage & Tobacco                         5134.0  13700.805921
France                                           5205.0  19690.707166
Germany                                          5135.0  20779.392795
Greece                                            629.0  22546.732909
Health Care                                      5152.0  19281.505862
Health Care Equipment & Services                 4231.0  11953.886126
Household & Personal Products                    4075.0  10128.621840
Industrials                                      5203.0  15774.012070
Information Technology                           5104.0  20135.244710
Insurance                                        5118.0  14168.707229
Ireland                                          2980.0  27355.392953
Italy                                            5090.0  22860.127151
Materials                                       10394.0  17020.710371
Media                                            5122.0  19787.007497
Netherlands                                      5117.0  20411.225914
Norway                                           5085.0  21513.245939
Pharmaceuticals, Biotechnology & Life Sciences   5146.0  20301.095725
Portugal                                          995.0  20075.792362
Real Estate                                      5159.0  12710.664896
Retailing                                        5118.0  19178.168152
Semiconductors & Semiconductor Equipment         1269.0  24984.591805
Software & Services                              4185.0  17930.021840
Spain                                            5104.0  19388.530760
Sweden                                           5106.0  15573.625774
Switzerland                                      5116.0  20449.133737
Technology Hardware & Equipment                  2439.0  23660.443460
Telecommunication Services                      10194.0  18091.337336
Transportation                                   5108.0  21191.626782
United Kingdom                                   5128.0  18241.182098
Utilities                                       10226.0  13026.141795

                                                                      \
                                                         std     min
Segment
Austria                                         10528.250888  1591.2
Automobiles & Components                        23379.624399  2671.6
Banks                                            7979.747222  2683.6
Belgium                                          7263.645055  2829.8
Capital Goods                                    5125.653618  4070.6
Commercial & Professional Services               8966.738452  1444.8
Consumer Discretionary                           6263.730825  5700.2
Consumer Durables & Apparel                      6588.557545  1852.0
Consumer Services                                8480.957509  1558.6
Consumer Staples                                 5430.116598  4184.6
Denmark                                         14239.234054  5173.6
Diversified Financials                           9616.574953  3088.8
Energy                                          62664.955958  4239.2
Europe                                           6416.623182  8340.4
Financials                                       4539.947243  6844.0
Finland                                          7808.787166  3464.4
Food & Staples Retailing                         6726.340563  1588.8
Food, Beverage & Tobacco                         5346.396222  2713.8
France                                           5509.092458  6505.0
Germany                                          6404.706024  5893.2
Greece                                          20102.503190  3641.2
Health Care                                      8655.924611  2864.8
Health Care Equipment & Services                 6542.121628  2227.4
Household & Personal Products                    4980.296550  1243.0
Industrials                                      5692.834171  6050.6
Information Technology                          18589.470635  2614.0
Insurance                                        9338.950903  2867.0
Ireland                                         32848.269491  2834.0
Italy                                           13476.164806  4449.6
Materials                                        5819.094400  2771.4
Media                                            8385.135219  1434.6
Netherlands                                      7762.536878  5072.6
Norway                                          29778.265171  3047.8
Pharmaceuticals, Biotechnology & Life Sciences   9845.419054  2538.8
Portugal                                        16674.276962  2675.4
Real Estate                                      8845.235939  2225.0
Retailing                                        9449.506541  2554.2
Semiconductors & Semiconductor Equipment        19470.906852  3170.4
Software & Services                             14819.601243  2935.2
Spain                                           12075.863347  3028.8
Sweden                                           5196.338522  4765.6
Switzerland                                     12210.407720  4543.6
Technology Hardware & Equipment                 29612.077788   666.8
Telecommunication Services                      10382.369062  3027.4
Transportation                                  14951.467345  2071.4
United Kingdom                                   7799.174943  4664.2
Utilities                                        7925.049269  2951.2

                                                                             \
                                                     25%      50%       75%
Segment
Austria                                          8133.65  11936.2  18202.25
Automobiles & Components                        11990.85  15660.1  20398.60
Banks                                           10288.55  13786.9  17394.30
Belgium                                         12213.20  15436.2  21504.20
Capital Goods                                   11443.75  13781.3  18284.00
Commercial & Professional Services               7791.70  10152.8  17727.35
Consumer Discretionary                          15413.80  19399.0  24841.05
Consumer Durables & Apparel                     12956.50  16950.7  20911.40
Consumer Services                                7045.75  10295.4  17240.15
Consumer Staples                                10028.20  15168.8  18421.00
Denmark                                         14425.80  20691.8  30955.20
Diversified Financials                          11956.80  14225.6  21886.00
Energy                                          12840.00  15953.2  20862.00
Europe                                          16645.20  19750.4  22765.60
Financials                                      12260.00  15234.2  18155.15
Finland                                          7756.40   9918.4  16443.20
Food & Staples Retailing                         8435.20  12370.4  18245.00
Food, Beverage & Tobacco                         8830.20  14453.7  17364.45
France                                          16066.20  20175.6  23332.20
Germany                                         15290.70  20306.6  26120.70
Greece                                          11393.80  17245.6  25828.60
Health Care                                     10581.00  21323.7  25959.85
Health Care Equipment & Services                 6115.10  11841.2  15857.10
Household & Personal Products                    5288.10  10552.8  13548.90
Industrials                                     11799.30  14087.0  20267.40
Information Technology                          11659.95  16887.3  22606.85
Insurance                                        7216.80  11630.8  17906.00
Ireland                                         13810.95  19138.5  32274.55
Italy                                           16175.50  21366.4  26645.30
Materials                                       12731.40  16158.0  20487.80
Media                                           12775.10  19526.1  26413.40
Netherlands                                     14384.40  20489.6  24322.20
Norway                                          12777.80  17454.8  27151.60
Pharmaceuticals, Biotechnology & Life Sciences  11011.10  21551.6  27701.65
Portugal                                        11221.80  15658.8  24966.60
Real Estate                                      6105.80   9245.0  16441.70
Retailing                                       12211.25  17986.4  24044.70
Semiconductors & Semiconductor Equipment        14894.00  21819.6  32221.80
Software & Services                              9033.60  13679.0  22631.00
Spain                                           11178.05  15043.4  21652.80
Sweden                                          11516.00  15233.1  18840.20
Switzerland                                     13579.70  16139.7  21442.70
Technology Hardware & Equipment                  9913.80  15914.0  29346.50
Telecommunication Services                      11241.00  14030.6  24095.00
Transportation                                  13978.05  18836.9  25414.95
United Kingdom                                  12410.15  16545.0  20124.15
Utilities                                        7593.00  10240.2  17284.20


                                                      max
Segment
Austria                                           76729.4
Automobiles & Components                        1395481.6
Banks                                             79602.4
Belgium                                           77491.4
Capital Goods                                     40595.2
Commercial & Professional Services               125395.8
Consumer Discretionary                            43778.2
Consumer Durables & Apparel                       56396.6
Consumer Services                                 77777.8
Consumer Staples                                  35485.8
Denmark                                          122304.0
Diversified Financials                            72071.2
Energy                                           751569.8
Europe                                            38752.0
Financials                                        48380.2
Finland                                           59538.0
Food & Staples Retailing                          58367.6
Food, Beverage & Tobacco                          34651.4
France                                            47612.6
Germany                                           53535.0
Greece                                           141787.8
Health Care                                       56606.0
Health Care Equipment & Services                  71843.4
Household & Personal Products                     45649.6
Industrials                                       37953.2
Information Technology                           356156.8
Insurance                                         77403.0
Ireland                                          899380.8
Italy                                            353000.0
Materials                                         48718.0
Media                                             66545.6
Netherlands                                       85074.0
Norway                                          1427762.0
Pharmaceuticals, Biotechnology & Life Sciences    59467.6
Portugal                                         384581.2
Real Estate                                       57304.4
Retailing                                         62154.6
Semiconductors & Semiconductor Equipment         388203.6
Software & Services                              256883.4
Spain                                             62704.6
Sweden                                            63687.8
Switzerland                                       66835.8
Technology Hardware & Equipment                  624882.8
Telecommunication Services                       195607.4
Transportation                                   274000.0
United Kingdom                                    44004.6
Utilities                                         85218.4

### Write to file

In [32]:
xw = pd.ExcelWriter('../data/processed/final_output.xlsx')
billing_by_ctry.to_excel(xw, sheet_name='Output', index=False, startrow=3)
billing_by_period.to_excel(xw, sheet_name='Output', index=False, startcol=4, startrow=3)
segment_summary_stat.to_excel(xw, sheet_name='Segment Summary Stats')
xw.close()